crawler/bitbucket.go
crawler/crawler.go
crawler/domain.go
crawler/github.go
crawler/gitlab.go
domains.yml

The domains are chosen randomly from the basic-auth array in domains.yml

[#157242255] Add multiple basic auth token on domains configuration

---

cmd/all.go
cmd/single.go
crawler/domain.go

Ignore and delete interrupted domains cleaning redis data.

[#157169498] Ignore interrupted domains

---

.dockerignore
Dockerfile
cmd/crawl.go
cmd/one.go
crawler/bitbucket.go
crawler/cloneRepository.go
crawler/crawler.go
crawler/github.go
crawler/gitlab.go

Add repository clone after file save.

[#156416605] Repositories git clone

---

.env.example
Dockerfile
README.md
config.toml.example
docker-compose-crawler.yml.example
docker-compose-prod.yml
docker/elasticsearch/config/searchguard/sg_roles.yml

I had to make these fixes in order to get it running correctly in the production environment.

Fixes for correct deployment

---

Gopkg.lock

[#159991883] Update publiccode-parser to latest version

---

.gitignore
crawler/crawler.go
crawler/saveToFile.go
docker-compose.yml.example

Integrates the publiccode-issueopener script Docker image in sample docker-compose

Issueopener integration

---

cmd/crawl.go
cmd/one.go
crawler/crawler.go
crawler/elasticClient.go
crawler/publiccode_model.go
crawler/saveToElasticsearch.go
crawler/saveToFile.go
docs/crawler.md
docs/deploy.md
docs/docs.md
docs/fileAndFolders.md
docs/jekyll.md
docs/mappingElasticsearch.md
docs/references.md
elasticsearch/php/config.inc.dist
elasticsearch/php/generatorRandomDocuments.php
elasticsearch/php/mappings/software_0.1.json
elasticsearch/scripts/createIndex.sh
elasticsearch/scripts/document.json
elasticsearch/scripts/insertDocument.sh
jekyll/firstSoftwareOpenSource.go
jekyll/firstSoftwareRiuso.go
jekyll/software_mapping.go
jekyll/softwares.go
main.go

- Add unique id as hashed git url (in both jekyll data and elasticsearch).
- Replace alias removal with unique index 'publiccodes' for cleaner architecture and update advantages.
- Add ES field "crawltime" to find old (or outdated) publiccodes.

[#159165552] Add repository Id

---

crawler/saveToElasticsearch.go
jekyll/firstSoftwareOpenSource.go
jekyll/firstSoftwareRiuso.go
jekyll/softwares.go

Add absolute urls in ES for Logo, Monochrome logo and screenshots.

[#161184689] Add absolute urls in ES.

---

.gitignore
crawler/cmd/list.go
crawler/crawler/crawler.go
crawler/crawler/whitelist.go
crawler/go.sum
crawler/whitelist/publishers.yml.example
crawler/whitelist/thirdparty.yml

We need to have this list in the repository so that people can open pull requests on it to add their repositories.

Store the whitelist of third-party software in the repository

---

crawler/crawler/bitbucket.go
crawler/crawler/clientApi.go
crawler/crawler/crawler.go
crawler/crawler/domain.go
crawler/crawler/github.go
crawler/crawler/gitlab.go
crawler/go.mod
crawler/go.sum

Due to deadlocks, the crawler was not processing the entire list of publishers.

Fix deadlocks

---

crawler/config.toml.example
crawler/elastic/elastic.go
crawler/go.sum
crawler/ipa/amministrazioni.go
elasticsearch/config/searchguard/sg_roles.yml

This PR changes how we fetch and store the data from IndicePA. See https://github.com/italia/developers-italia-onboarding/issues/72 for more details.
We should merge this only after testing that the new structure works well.

Change our IndicePA index to a flat structure

---

crawler/whitelist/thirdparty.yml

Added the external repo for LibreOffice powered by CIB

Added LibreOffice powered by CIB

---

.github/PULL_REQUEST_TEMPLATE/thirdparty.md

Add PR template for adding third party sw. 
This is a draft PR, waiting to have the stable link to the policy. 
@biancini please review.

Add PR template for adding third party sw

---

crawler/whitelist/thirdparty.yml

Proposal to add Knowage to third party software list. Knowage is an open source suite for modern Business Analytics.
Website: https://www.knowage-suite.com/site/home/
Success stories: https://www.knowage-suite.com/site/resources/success-stories/
Repository: https://github.com/KnowageLabs/Knowage-Server

Adding Knowage: Open Source Suite for modern Business Analytics

---

crawler/crawler/whitelist.go
crawler/crawler/whitelist_test.go

mock ReadFile for whitelist reader test

whitelist tests implemented injecting fake ReadFile

---

crawler/whitelist/thirdparty.yml

faunalia organization + DataPlotly repository

Add Faunalia organization

---

crawler/crawler/crawler.go
crawler/crawler/domain.go
crawler/crawler/saveToElasticsearch.go
crawler/domains.yml.example
crawler/go.mod
crawler/go.sum

A list of domains is supplied in `domains.yml` file, they represent a list of domains on which the authentication is possible.

Bump pcvalidator, use list of domain to support major code hosting

---

crawler/whitelist/thirdparty.yml

Fix thirdparty.yml

---

.github/workflows/main.yml
crawler/blacklist/blacklist.yml
crawler/whitelist/manual-reuse.yml
crawler/whitelist/thirdparty.yml

This aims to validate all yaml files in lists

feat: yaml linter ci

---

.github/workflows/release.yml
.goreleaser.yml
Dockerfile.goreleaser
crawler/go.mod
crawler/go.sum

GoReleaser will handle all software releases
Fix #158

Add goreleaser

---

docs/vitalityIndex.md
docs/vitalityIndexItaliano.md

This PR:
* adds a docs file regarding the vitality index. 
TODO:
Reviewers:

Add vitality index docs file

---

.circleci/config.yml

[#176] Remove deploy job from circleci since azure is in charge for that

---

crawler/jekyll/softwares.go

Fixes: https://github.com/italia/developers.italia.it/issues/601

fix wrong categories path in pc and add sort by score desc

---

crawler/crawler/crawler.go

Limit the amount of goroutines to 5 instead of one per repo to
avoid trashing the network and the system.
Should mitigate #170.

Limit the amount of goroutines when processing repos.

---

.env.example
README.md
crawler/domains.yml.example
docker-compose.yml

Use the pre-build elasticsearch image to be able to use the
development enviroment from the get go.

Use italia/publiccode-tools-elasticsearch.

---

crawler/crawler/crawler.go

Goroutines should be in line with number of CPUs to get best performance.

feat: goroutines number as of cpus

---

crawler/whitelist/manual-reuse.yml

They are already present in onboarding list and was causing #185

Removing AgID and UniversitaDellaCalabria from manual-reuse.yml

---

crawler/crawler/crawler.go

Make logs for each repo available at
https://crawler.developers.italia.it/$hosting/$org/$repo/out.txt
Fix #213.
Note this needs an upcoming PR addressing security (#215).

feat: make logs available to the outside world

---

crawler/crawler/github.go
crawler/whitelist/thirdparty.yml

Plugin WordPress _WooCommerce Carta Docente_

WC Carta Docente

---

crawler/crawler/gitlab.go

Use /api/v4/projects with on-prem instances

---

crawler/crawler/crawler.go

Timestamp the public logs introduced in c154c0851ad.

feat: timestamp the public logs

---

README.md
crawler/crawler/crawler.go

feat: save the public logs as JSON

---

crawler/whitelist/manual-reuse.yml

**Do not merge before https://github.com/italia/design-comuni-pagine-statiche/pull/1**

Add website template for municipalities

---

crawler/whitelist/thirdparty.yml

Signalen is an open source process and task system for governments, which automatically categorizes and routes reports about public space for processing by the appropriate handler. Developed by the municipality of Amsterdam.

Add Signalen to thirdparty list

---

crawler/crawler/bitbucket.go
crawler/crawler/bitbucket_test.go
crawler/crawler/domain.go
crawler/crawler/github.go
crawler/crawler/github_test.go
crawler/crawler/gitlab.go
crawler/crawler/gitlab_test.go

refactor: always use go-vcsurl

---

crawler/crawler.go
metrics/prometheus.go

 feat: print summary when the crawling is done

---

.golangci.yaml
apiclient/apiclient.go
cmd/download_publishers.go
cmd/one.go
common/repository.go
common/split_fullname.go
crawler/crawler.go
git/clone_repository.go
git/repo_activity.go
metrics/prometheus.go
scanner/bitbucket.go
scanner/github.go
scanner/gitlab.go

Enable some more linters

---

.golangci.yaml
common/repository.go
metrics/prometheus.go
scanner/github.go

refactor!: enable gosec linter

---

.golangci.yaml
apiclient/apiclient.go
crawler/crawler.go
git/repo_activity.go
scanner/bitbucket.go
scanner/github.go
scanner/gitlab.go

chore: enable lll linter

---

.golangci.yaml
cmd/version.go

chore: enable forbidigo linter

---

.gitignore
charts/publiccode-crawler/.helmignore
charts/publiccode-crawler/Chart.yaml
charts/publiccode-crawler/templates/_helpers.tpl
charts/publiccode-crawler/templates/cronjob.yaml
charts/publiccode-crawler/templates/secret.yaml
charts/publiccode-crawler/values.yaml

feat: add Helm chart
