cmd/all.go
cmd/single.go
crawler/crawler.go
httpclient/httpclient.go
plugins/github/plugin.go

Add goroutines for single repository retrieved from all repository list APIs (it is necessary in order to obtain the "main branch" property).

[#157470367] Improve GitHub retrieve performance

---

cmd/crawl.go
cmd/one.go
crawler/repo_activity.go
ipa/amministrazioni.go
vitality-ranges.yml

Activity ranges (calculated daily):
- usercommunity (before that day): 0-28 authors in values are 4-36 points. Max 36 points.
- codeActivity per day (commits+merges): 0-35 in value are 2-60 points. Max 60 points.
- releaseHistory per day (tags per day): points are: number of tags + 20. Max 50 points.
- longevity (repository age): <1y value 20 points, 1y<age<2y value 30 points, more 35 points

[#159065604] Update activity ranges.

---

docker-compose-prod.yml

We're serving the website directly from the nginx server of the host server, so no need for serving it through traefik.

Comment the nginx container as it's not needed in production

---

crawler/crawler.go
crawler/saveToFile.go

With this change when a bad publiccode.yaml file is found the url is saved to a file, used later by the publiccode-issueopener script.
As requested by Riccardo Iaconelli from Developers Italia I'm developing a simple tool that automatically opens an issue on Github repos containing bad publiccode.yaml files.
(https://github.com/cantierecreativo/publiccode-issueopener)

Save bad publiccode yaml urls to file

---

crawler/go.mod
crawler/go.sum
crawler/jekyll/softwares.go
docs/mappingElasticsearch.md

As of now this crawler expects three-letter language codes as sub-keys of `description/`, according to [publiccode.yml 0.1](https://github.com/italia/publiccode.yml/tree/0.1).
We're switching to BCP 47 in 0.2. The Go parser was already updated so that it accepts two or thee letter codes (plus all the BCP 47 set) and always returns the canonicalized BCP 47 form.
This is a **breaking change**: we need to update all the current entries in Elasticsearch and make sure the new mapping is applied.

Switch to BCP 47 language codes

---

crawler/whitelist/thirdparty.yml

Proposal to add Idra to third party software list. Idra is a web application that federates and existing Open Data Management Systems  based on different technologies providing a unique and standard access point via open API. Idra harmonise metadata of open dataset supporting international standards (e.g. DCAT-AP) and guidelines. Demo: https://idra.eng.it

Added Idra - Open Data Federation Platform

---

crawler/config.toml.example
crawler/elastic/elastic.go
crawler/ipa/amministrazioni.go

This PR improves the IndicePA data in two ways:
* it imports the 105k+ OU records from IndicePA in addition to the AOOs that we already have, thus making our index more complete;
* it imports the "Tipologia" (Type) field too, so that we can filter by entity type.

Improvements to the IndicePA import

---

crawler/cmd/download-whitelist.go

When multiple entries with same IPA code it would aggregates orgs url under same object.
#105

Fixes download whitelist aggregation orgs #105

---

crawler/crawler/saveToElasticsearch.go

This will fixes https://github.com/italia/developers.italia.it/issues/473 all dots in slugs will be replaced by `_`. Jekyll misunderstand dots and tends to interpretate them as subfolders.

Fix developers.italia.it#473 dots in slugs are replaced by an underscore

---

crawler/crawler/github.go
crawler/crawler/saveToElasticsearch.go

The real problem was [here](https://github.com/italia/developers-italia-backend/blob/e8783570794edda42d6aabb8bbd246caa830e3ef/crawler/crawler/github.go#L274), whether querying api for one of repositories inside an organisation or user returns an error that return caused `exit` from repositories loop and skipping the evaluation of others repo in list.
Will fixes #112

Fixes #112 exiting from repos loop whether api returns error

---

crawler/crawler/gitlab.go

Gitlab platform on premises failed to get raw url for `publiccode.yml`.

Gitlab on prem failed to get publiccode raw url

---

crawler/crawler/repo_activity.go
crawler/crawler/saveToFile.go

According to #110 this pr aims to have a more verbose logs on `bad_publiccodes.lst` file getting troubleshooting easier.
It also fixes a missing return.

Logs more verbose #110

---

crawler/whitelist/thirdparty.yml

Stanza Del Cittadino and a plugin for OpenAgenda to perform automatic translation in multiple languages of events using AWS Translate.

Update thirdparty.yml from Opencontent

---

crawler/whitelist/thirdparty.yml

Added reference to GovPay's github repository, open source implementation of PAP (Porta Applicativa dei Pagamenti) introduced by pagoPA specifications.

Added project GovPay

---

README.md
crawler/crawler/crawler.go
crawler/crawler/crawler_test.go
crawler/crawler/whitelist.go

Crawler will check if a match exists between IPA code in whitelists and in its related `publiccode.yml`. This validation process is skipped using `one` command since in that mode the repository given could not exists in crawler's whitelists.

IPA code were not matched correctly

---

README.md
crawler/cmd/one.go
crawler/crawler/crawler.go

In this mode will be evaluated one single repository at the time. IPA code will be matched with ones in whitelist, if organization is present, otherwise will be set to null and `slug` will have a random code in the end (instead of ipa code), furthermore, ipa code validation, a simple check within whitelists (which ensure that code belongs to selected PA), will be skipped.

one mode now will checks whitelist for IPA validation and slug generation

---

README.md
crawler/cmd/delete.go
crawler/crawler/saveToElasticsearch.go

As for #139 crawler is now able to delete item in Elasticsearch using `publiccode.url` as search parameter. It will also remove them from datafile used by Developers Italia's jekyll to build software catalog.
Administrations in data files and Elasticsearch are calculated from scratch due to its stateless implementation

Delete command for crawler

---

crawler/httpclient/httpclient.go

When doing http get and got a failed httpstatus, crawler will retry for [times](https://github.com/italia/developers-italia-backend/blob/master/crawler/httpclient/httpclient.go#L29) applying different rules based on error type.
Whether an unknown status is received that counter were not incremented and an infinite loop was triggered.

Counter for failed http did not increment

---

crawler/jekyll/softwares.go

fixes #150 
Related softwares now have `codiceIPA` and they can be distinguished from third party.

Related softwares now have codiceIPA

---

crawler/config.toml.example
crawler/crawler/crawler.go

This PR:
* adds the `ACTIVITY_DAYS` const in the `config.toml` and reads it.
Fixes #172 
We should probably set a `viper.SetDefault("ACTIVITY_DAYS", "60")` in the initialization or default to `60` if that makes sense.

[#172] Add activity days in config file

---

crawler/go.mod
crawler/go.sum

Update to publiccode-parser go v1.1.4 which uses latest go-vcsurl.
Fix #85.

Update to publiccode-parser go v1.1.4.

---

crawler/crawler/cloneRepository.go

Show the git output when clone or fetch fail in order to have
more information on the nature of the failure.
Related to #185.

Show the git output when clone or fetch fail.

---

crawler/cmd/crawl.go
crawler/start.sh

crawl now skips publishers if they contain an organization that
is already been seen. The order of preference of the YAML files
containing the publishers is deduced by the ordering of the arguments
to the crawl commmand.
Note we don't check for duplicates repos, only organizations.
Fix #185.

Skip publishers if they contain duplicate orgs.

---

README.md

Used https://github.com/badges/shields, set the Azure DevOps icons
Should close #182

Adding Azure DevOps badge

---

crawler/blacklist/blacklist.yml

We can't exclude missing repos by using blacklists because the
crawler won't see them in the first place and thus it won't
filter them out (and remove them from Elasticsearch) using the
blacklist.
This reverts commit 5e72b33e0c2b3809a8b184c70a15d7de359ce789.

Revert "chore: arpa-puglia repos blacklisted, no longer available"

---

.github/workflows/test_and_publish_docker_image.yml

Explicitly use actions/checkout so the .git directory is present when
building. git's history is used to infer the crawler's version.

chore(ci): use actions/checkout when building

---

.github/workflows/test_and_publish_docker_image.yml

docker/build-push-action uses BuildKit, so we need to
go through it in order to keep the .git directory around.

chore(ci): actually keep the .git directory at build

---

crawler/blacklist/blacklist.yml

Re-enable formerly empty repository blacklisted in bbb61860616f9.

chore: re-enable cmdrc/gasplanet repository

---

crawler/start.sh

ElasticSearch is always up when the job is started.

refactor: don't wait for ElasticSearch

---

crawler/elastic/elastic.go

Map name.keyword to a keyword field so that we can sort by it.

feat: add name field as keyword in Elasticsearch

---

crawler/whitelist/manual-reuse.yml

This PR:
* adds the new `api-oas-checker` location under `/italia`

chore: add new oas checker repo

---

crawler/whitelist/thirdparty.yml

Il software si sta arricchendo di svariati microservizi, quindi stiamo migrando tutti i repository sotto un unico gruppo.

Updated repository URL of stanzadelcittadino

---

crawler/go.mod
crawler/go.sum

Update publiccode-paser-go to v1.2.4 to get the latest
amministrazioni.txt.

chore: update publiccode-parser-go to v1.2.4

---

crawler/crawler/crawler.go
crawler/whitelist/thirdparty.yml

Publishers named "_"" are special and get to skip the additional checks,
like the publiccode.yml's url needing to be on the same repo.
They can be used to add repositories and organizations, under the
crawler's admins control, that describe arbitrary repos
(eg. metarepos for other entities)
This is an hack while we come up with a more elegant solution, after
the crawler's refactor.

feat: make publishers named "_" skip the same-repo check

---

crawler/crawler/cloneRepository.go
crawler/crawler/crawler.go

Use the URL in publiccode.yml when cloning the repo locally, so the
vitality of software using metarepos is calculated against the actual software
repository instead of the metarepo itself.
Fix #264.

fix: use publiccode.yml's url when cloning the repo locally

---

.github/workflows/release.yml

Goreleaser is not in charge of the Docker image build: that's done
in a different workflow (test_and_publish_docker_image.yml).

chore: don't login to DockerHub on release

---

crawler/crawler/cloneRepository.go

In order to save disk space, make bare clones of repositories filtering out blobs.
Fixes #249

feat: clone bare repositories without blobs

---

publishers.thirdparty.yml

Spunta is a simple checklist manager, already adopted by a few Red Cross local groups for routine revision of equipments. Probably this is interesting also to other kind of subjects, even within public administration.

added Spunta to third party list

---

publishers.thirdparty.yml

Green Pass Turnstile è un sistema di accesso agli edifici con verifica del Green Pass europeo per il Covid-19 e Tessera Sanitaria

Aggiunto GreenPass Turnstile

---

crawler/crawler.go

refactor: use err.Message() in error log

---

scanner/github.go

fix: don't crash when publiccode.yml is a symlink

---

scanner/github.go

Repos should be inside GitHub organizations, but we have a few Public Administrations which still use GitHub users.
Let's bring the support back until they all migrate to GitHub orgs.

fix: bring back listing repos for GitHub users

---

crawler/crawler.go

The logic for MAIN_PUBLISHER_ID was inverted: we need to do additional validations only when the it's different from the Publisher id.

fix: use the right logic for MAIN_PUBLISHER_ID

---

scanner/github.go

Handle secondary API limit in all calls and sleep for a random time if the API response doesn't contain the Retry-After header.

feat: handle secondary limit in all GitHub calls

---

apiclient/apiclient.go
crawler/crawler.go

Previously we only created a new Software entity only when the
publiccode.yml is valid, so in case of a new repo with an invalid
publiccode.yml nothing was added.
This means the new software didn't exist from the API's point of view,
and because of that publiccode-issueopener can't notify the maintainers about
the errors, even if new repos are arguably the ones where error reporting and
a little hand holding are more valuable.
So add the software even if publiccode.yml is invalid, setting active to
false.
We will re-activate software whenever publiccode.yml is valid *only*
if it was previously added automatically for the first time as inactive.
Fix #325.

feat: create Software even if publiccode.yml is invalid

---

config.toml.example
crawler/crawler.go
git/clone_repository.go
git/repo_activity.go
main.go

Make the crawler work when there's no config.toml.
Also, change CRAWLER_DATADIR to just DATADIR.
Fix #318.

feat!: set default config values

---

apiclient/apiclient.go

Fix the bug introduced in 0e4e25c01405 that returned only the first 10 Publishers.

fix: properly get all the Publishers

---

Dockerfile
start.sh

Get publishers on run instead of in the build of the Docker image, so every run is up to date with the current publishers.

feat: get publishers files on run

---

.golangci.yaml
crawler/crawler.go

Add gomnd to the list of disabled linters because it the majority of issues it catches are not really issues.

refactor: add constant and disable the gomnd linter

---

.github/workflows/release.yml

archives.replacements was removed in 1.19.0:
https://goreleaser.com/deprecations/#archivesreplacements.
That should've probably been a new major version on goreleaser's side.
(see also https://github.com/pulumi/pulumi/issues/13312)

chore(release): pin goreleaser to v1.18.2

---

crawler/crawler.go
scanner/bitbucket.go
scanner/github.go
scanner/gitlab.go

The number of go routines could explode the more Publishers there are, despite out bottleneck being the GitHub API rate limiting.
Try to be more conservative with go routines.

fix: reduce go routines and add debug logging

---

go.mod
go.sum

Fix infinite loop when checking for reachability of URLs in the publiccode.yml, when the response is not a 2xx or the error statuses explicitly handled by httpclient-lib-go.
See https://github.com/italia/publiccode-parser-go/pull/190.

fix: infinite loop in publiccode.yml validation
